name = "projeto-integracao"
main = "server/_core/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "projeto-integracao-db"
database_id = "894a6bad-e96e-4c1e-9ab9-55a91f77bbd9"
