name = "integrabase"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/public"

[[d1_databases]]
binding = "DB"
database_name = "projeto-integracao-db"
database_id = "894a6bad-e96e-4c1e-9ab9-55a91f77bbd9"

# Environment variables
[vars]
NODE_ENV = "production"
VITE_APP_TITLE = "Sistema Integração Base&Profil"
VITE_APP_ID = "integrabase-prod"
OWNER_EMAIL = "admin@inter.com"
